// This file is autogenerated. Changes will be overwritten.
#include "XG2Y6YZZKZ/moc_AddNoteFlow.cpp"
#include "XG2Y6YZZKZ/moc_GoogleTranslateProvider.cpp"
#include "XG2Y6YZZKZ/moc_TranslationService.cpp"
#include "XG2Y6YZZKZ/moc_TtsPipelineService.cpp"
